language: node_js
node_js:
  - "10"
sudo: enabled
branches:
  only:
    - master
    - dev
install:
  - yarn install
script:
  - yarn build

notifications:
  email:
    - guiyumin@yahoo.com
  slack: 
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
      - "Commit: *%{commit} : %{commit_message}*"
      - "Build Status: *%{result}* "
      - "Build Duration: *%{duration}* "
    rooms:
      - jekyllpay:ayUfNRYKnjoK3WsJle9Ec0YI
    on_success: always
    on_failure: always