language: node_js
node_js:
  - "8"
sudo: enabled
branches:
  only:
    - master
    - dev
install:
  - yarn install
script:
  - yarn build

notifications:
  slack: 
    rooms:
      - jekyllpay:ayUfNRYKnjoK3WsJle9Ec0YI
    on_success: always
    on_failure: always